export const SET_ACTIVE_CONTACT = 'SET_ACTIVE_CONTACT'
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY'
export const API_REQUEST_CONTACTS = 'API_REQUEST_CONTACTS'
export const API_RECEIVE_CONTACTS = 'API_RECEIVE_CONTACTS'
